import type { DB } from "./types";

const now = new Date();
const iso = (daysFromNow: number) => new Date(now.getTime() + daysFromNow * 86400000).toISOString();

export function seedDB(): DB {
  return {
    schemaVersion: 2,
    language: "en",
    currentUserId: "u_me",
    users: [
      {
        UserID: "u_me",
        Email: "me@persimmon.factory",
        DisplayName: "Me (Mike)",
        ProfileImage: null,
        CurrentMood: "Neuna / overwhelmed",
        CurrentLoad: 5,
        HelpNeeded: true,
        LastCheckIn: iso(0),
      },
      {
        UserID: "u_mum",
        Email: "mum@persimmon.factory",
        DisplayName: "Mum",
        ProfileImage: null,
        CurrentMood: "Fine",
        CurrentLoad: 2,
        HelpNeeded: false,
        LastCheckIn: iso(-1),
      },
      {
        UserID: "u_dad",
        Email: "dad@persimmon.factory",
        DisplayName: "Dad",
        ProfileImage: null,
        CurrentMood: "Elster / focused",
        CurrentLoad: 3,
        HelpNeeded: false,
        LastCheckIn: iso(-1),
      },
      {
        UserID: "u_partner",
        Email: "partner@persimmon.factory",
        DisplayName: "Partner",
        ProfileImage: null,
        CurrentMood: "Goldie / energetic",
        CurrentLoad: 2,
        HelpNeeded: false,
        LastCheckIn: iso(-2),
      },
    ],
    connections: [
      // Me <-> Mum
      c("cn1", "u_me", "u_mum", "Mum", true),
      c("cn2", "u_mum", "u_me", "Son", false),
      // Me <-> Dad
      c("cn3", "u_me", "u_dad", "Dad", true),
      c("cn4", "u_dad", "u_me", "Son", false),
      // Me <-> Partner
      c("cn5", "u_me", "u_partner", "Partner", true),
      c("cn6", "u_partner", "u_me", "Partner", false),
      // Mum and Dad can see and assign to one another.
      c("cn7", "u_mum", "u_dad", "Partner", true),
      c("cn8", "u_dad", "u_mum", "Partner", true),
      // Deliberately no connection between Mum/Dad and Partner.
    ],
    tasks: [
      t({
        TaskID: "t_thesis",
        Title: "Thesis deadline",
        OwnerUser: "u_me",
        Category: "Work / Study",
        DeadlineBucket: "Soon",
        Deadline: iso(6),
        Priority: 5,
        ExpectedLoad: 5,
        WhyImportant: "Everything else in the year depends on this landing.",
        Status: "In Progress",
        Visibility: "MY CONNECTIONS",
      }),
      t({
        TaskID: "t_paperwork",
        Title: "Application paperwork",
        OwnerUser: "u_me",
        Category: "Money / Admin",
        DeadlineBucket: "Soon",
        Deadline: iso(10),
        Priority: 4,
        ExpectedLoad: 4,
        WhyImportant: "Forms drain me more than the work itself.",
        Status: "Blocked",
        BlockerType: "I need information",
        Visibility: "MY CONNECTIONS",
      }),
      t({
        TaskID: "t_private",
        Title: "Plan the anniversary trip",
        Description: "Private task requested by Partner.",
        OwnerUser: "u_me",
        RequestedByUser: "u_partner",
        Category: "Social",
        DeadlineBucket: "Later",
        Priority: 3,
        ExpectedLoad: 4,
        WhyImportant: "It matters to Partner that I plan it myself.",
        Status: "In Progress",
        Visibility: "MY CONNECTIONS",
        DetailLevel: "LOAD ONLY",
      }),
      t({
        TaskID: "t_toothpaste",
        Title: "Buy toothpaste",
        OwnerUser: "u_me",
        Category: "Errands",
        DeadlineBucket: "Today",
        Deadline: iso(0),
        Priority: 2,
        ExpectedLoad: 1,
        Status: "Sorted",
        Visibility: "MY CONNECTIONS",
      }),
      t({
        TaskID: "t_reimb",
        Title: "Recover HK$300 reimbursement",
        OwnerUser: "u_me",
        RequestedByUser: "u_dad",
        Category: "Money / Admin",
        DeadlineBucket: "Soon",
        Deadline: iso(4),
        Priority: 3,
        ExpectedLoad: 2,
        WhyImportant: "I dislike unresolved money and want loose financial matters closed.",
        Status: "Sorted",
        Visibility: "MY CONNECTIONS",
        ReminderPermission: "One reminder",
        AssignmentResponse: "📥 Received",
      }),
      t({
        TaskID: "t_dump1",
        Title: "Email professor",
        OwnerUser: "u_me",
        Status: "Inbox",
        Priority: 3,
        ExpectedLoad: 2,
      }),
      t({
        TaskID: "t_dump2",
        Title: "Book dentist",
        OwnerUser: "u_me",
        Status: "Inbox",
        Priority: 3,
        ExpectedLoad: 2,
      }),
      t({
        TaskID: "t_mum1",
        Title: "Sort out the kitchen cupboard",
        OwnerUser: "u_mum",
        Category: "Household",
        Priority: 2,
        ExpectedLoad: 2,
        Status: "Sorted",
        Visibility: "MY CONNECTIONS",
      }),
      t({
        TaskID: "t_dad1",
        Title: "Chase insurance policy",
        OwnerUser: "u_dad",
        Category: "Money / Admin",
        Priority: 3,
        ExpectedLoad: 3,
        Status: "Waiting for Someone",
        Visibility: "MY CONNECTIONS",
      }),
      t({
        TaskID: "t_partner1",
        Title: "Rebook the flights",
        OwnerUser: "u_partner",
        Category: "Errands",
        Priority: 3,
        ExpectedLoad: 3,
        Status: "In Progress",
        Visibility: "MY CONNECTIONS",
      }),
    ],
    steps: [
      s("st1", "t_paperwork", 1, "Find policy number", true),
      s("st2", "t_paperwork", 2, "Find phone number", false),
      s("st3", "t_paperwork", 3, "Call", false),
      s("st4", "t_paperwork", 4, "Upload document", false),
    ],
    projects: [],
    categories: [
      ...[
        "Work / Study",
        "Family",
        "Household",
        "Money / Admin",
        "Health",
        "Social",
        "Errands",
        "Other",
      ].flatMap((name, index) =>
        ["u_me", "u_mum", "u_dad", "u_partner"].map((owner) => ({
          CategoryID: `cat_${owner}_${index}`,
          OwnerUser: owner,
          ProjectID: null,
          Name: name,
          ArchivedAt: null,
        })),
      ),
    ],
    assignments: [
      {
        AssignmentID: "as_private",
        TaskID: "t_private",
        RequesterUser: "u_partner",
        RecipientUser: "u_me",
        WhyImportant: "It matters to Partner that I plan it myself.",
        ExpectedLoad: 4,
        Deadline: null,
        ReminderPermission: "None",
        State: "accepted",
        LastMessage: "",
        CreatedAt: iso(-2),
        UpdatedAt: iso(-2),
      },
      {
        AssignmentID: "as_reimb",
        TaskID: "t_reimb",
        RequesterUser: "u_dad",
        RecipientUser: "u_me",
        WhyImportant: "I dislike unresolved money and want loose financial matters closed.",
        ExpectedLoad: 2,
        Deadline: iso(4),
        ReminderPermission: "One reminder",
        State: "received",
        LastMessage: "",
        CreatedAt: iso(-1),
        UpdatedAt: iso(-1),
      },
    ],
    supportRequests: [],
    notifications: [],
    access: [],
    persimmons: [
      {
        EventID: "pe1",
        FromUser: null,
        ToUser: "u_me",
        Task: null,
        Amount: 4,
        Reason: "Starting week credit",
        Timestamp: iso(-3),
      },
      ...["u_mum", "u_dad", "u_partner"].map((u, i) => ({
        EventID: `pe_seed_${i}`,
        FromUser: null,
        ToUser: u,
        Task: null,
        Amount: 3,
        Reason: "Starting week credit",
        Timestamp: iso(-3),
      })),
    ],
    characters: CHARACTERS,
    pings: [],
    dumps: [],
  };
}

function c(id: string, viewer: string, owner: string, label: string, canAssign: boolean) {
  return {
    ConnectionID: id,
    OwnerUser: owner,
    ViewerUser: viewer,
    RelationshipLabel: label,
    CanSeeProfile: true,
    CanSeeLoad: true,
    CanAssignTasks: canAssign,
    Active: true,
  };
}

function s(StepID: string, Task: string, StepOrder: number, StepText: string, IsDone: boolean) {
  return { StepID, Task, StepOrder, StepText, IsDone };
}

function t(
  partial: Partial<DB["tasks"][number]> & { TaskID: string; Title: string; OwnerUser: string },
) {
  return {
    Description: "",
    RequestedByUser: null,
    Category: "Other" as const,
    CategoryID: null,
    ProjectID: null,
    ParentTaskID: null,
    Deadline: null,
    DeadlineBucket: "No deadline" as const,
    Priority: 3,
    ExpectedLoad: 3,
    WhyImportant: "",
    Status: "Inbox" as const,
    Visibility: "JUST ME" as const,
    DetailLevel: "FULL" as const,
    BlockerType: "" as const,
    ParkedThoughts: "",
    SupportRequested: [],
    ReminderPermission: "None" as const,
    LastReminder: null,
    AssignmentResponse: "" as const,
    Interesting: false,
    CreatedAt: new Date().toISOString(),
    CompletedAt: null,
    ...partial,
  };
}

export const CHARACTERS = [
  {
    CharacterID: "bulu",
    DisplayName: "Bulu 紅耳布嚕",
    EnglishName: "Bulu",
    ChineseName: "紅耳布嚕",
    Nickname: "Control Tower",
    Role: "Control tower, reminders, announcements, noticing unfinished things.",
    Image: null,
    ShortPrompt: "Control Tower: 4 unsorted packages are waiting.",
  },
  {
    CharacterID: "teddi",
    DisplayName: "Teddi 喊包塔塔",
    EnglishName: "Teddi",
    ChineseName: "喊包塔塔",
    Nickname: "Minimum Viable Worker",
    Role: "Very-low-energy mode, shutdown, choosing minimum viable actions without shame.",
    Image: null,
    ShortPrompt: "Minimum viable worker mode. One tiny thing is enough.",
  },
  {
    CharacterID: "elster",
    DisplayName: "Elster 伊斯特 (柿務總管)",
    EnglishName: "Elster",
    ChineseName: "伊斯特",
    Nickname: "柿務總管",
    Role: "Factory operations, execution, logistics, completion, persimmon economy.",
    Image: null,
    ShortPrompt: "Shipment completed. Acceptable. Here is a persimmon.",
  },
  {
    CharacterID: "neuna",
    DisplayName: "Neuna 連環九殺貓",
    EnglishName: "Neuna",
    ChineseName: "連環九殺貓",
    Nickname: "The Breakdown Cat",
    Role: "Breaking down tasks, prioritisation, stopping spiralling.",
    Image: null,
    ShortPrompt: "Are we actually solving the task, or wasting time thinking about the task?",
  },
  {
    CharacterID: "nuffel",
    DisplayName: "Nuffel 攬枕狗",
    EnglishName: "Nuffel",
    ChineseName: "攬枕狗",
    Nickname: "Support Dog",
    Role: "Actionable support, body doubling, practical help, encouragement.",
    Image: null,
    ShortPrompt: "What kind of support helps here?",
  },
  {
    CharacterID: "goldie",
    DisplayName: "Goldie 小今",
    EnglishName: "Goldie",
    ChineseName: "小今",
    Nickname: "Novelty Scout",
    Role: "Play, novelty, curiosity, enjoyable tasks, aliveness.",
    Image: null,
    ShortPrompt: "Anything interesting hiding in the pile?",
  },
];
