/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FloorRouteImport } from './routes/floor'
import { Route as HarvestRouteImport } from './routes/harvest'
import { Route as SortingRouteImport } from './routes/sorting'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FloorRoute = FloorRouteImport.update({
  id: '/floor',
  path: '/floor',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestRoute = HarvestRouteImport.update({
  id: '/harvest',
  path: '/harvest',
  getParentRoute: () => rootRouteImport,
} as any)
const SortingRoute = SortingRouteImport.update({
  id: '/sorting',
  path: '/sorting',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/floor': typeof FloorRoute
  '/harvest': typeof HarvestRoute
  '/sorting': typeof SortingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/floor': typeof FloorRoute
  '/harvest': typeof HarvestRoute
  '/sorting': typeof SortingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/floor': typeof FloorRoute
  '/harvest': typeof HarvestRoute
  '/sorting': typeof SortingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/floor' | '/harvest' | '/sorting'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/floor' | '/harvest' | '/sorting'
  id: '__root__' | '/' | '/floor' | '/harvest' | '/sorting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FloorRoute: typeof FloorRoute
  HarvestRoute: typeof HarvestRoute
  SortingRoute: typeof SortingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/floor': {
      id: '/floor'
      path: '/floor'
      fullPath: '/floor'
      preLoaderRoute: typeof FloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvest': {
      id: '/harvest'
      path: '/harvest'
      fullPath: '/harvest'
      preLoaderRoute: typeof HarvestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sorting': {
      id: '/sorting'
      path: '/sorting'
      fullPath: '/sorting'
      preLoaderRoute: typeof SortingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FloorRoute: FloorRoute,
  HarvestRoute: HarvestRoute,
  SortingRoute: SortingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
